language: go
go:
  - 1.5

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

script:
  - go get -u github.com/golang/lint/golint
  - golint ./...
  - make test

before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr

after_success:
  - make ci
  - test "$TRAVIS_BRANCH" = "master" && ghr --username ojongerius --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
